sudo: false

language: node_js

node_js:
  - "node" # the latest stable nodejs

notifications:
  email: false

cache:
  yarn: true

env:
  global:
    - PATH=$HOME/.yarn/bin:$HOME/.local/bin:$PATH
  matrix:
    - CI_MATRIX_BUILD=true
    - CI_MATRIX_LINT=true
    - CI_MATRIX_TEST=true

matrix:
  allow_failures:
    - env: CI_MATRIX_TEST=true # TODO https://github.com/ReactiveX/IxJS/issues/2

before_install:
  # Use the latest yarnpkg because Travis' builtin yarn is not the latest.
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - which yarn # for debugging Travis
  - echo $PATH # for debugging Travis

script:
  - |
    if [ "$CI_MATRIX_BUILD" = "true" ]; then
      npm run build
    elif [ "$CI_MATRIX_LINT" = "true" ]; then
      npm run lint
    elif [ "$CI_MATRIX_TEST" = "true" ]; then
      npm run build
      npm run test
    else
      echo "This code path is run unexpectedly" 1>&2
      exit 1
    fi
