name: docs

on:
  push:
    branches:
      - master
    paths:
      - 'LICENSE'
      - 'README.md'
      - 'typedoc.js'
      - '.github/workflows/**'
      - 'src/**/*.ts'

jobs:
  update:
    name: Update Docs
    runs-on: ubuntu-latest
    container: node:16.15.1-bullseye
    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main
          persist-credentials: false
      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
      - name: Build Docs
        working-directory: main
        run: |
          set -x
          yarn --ignore-engines --non-interactive
          yarn doc
      - name: Copy Docs to gh-pages
        run: |
          rm -rf gh-pages/docs
          cp -r main/doc gh-pages/docs
      - name: Commit new docs
        working-directory: gh-pages
        run: |
          COMMIT_SHA=$(echo "${COMMIT_SHA}" | cut -c 1-7)
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add --all
          git commit --allow-empty -m "update docs from ${COMMIT_SHA}"
          git push
        env:
          COMMIT_SHA: ${{ github.sha }}
