name: Build pull request

concurrency:
  group: pr-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "master"

jobs:
  lint-pull-request:
    name: Lint
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: true
      matrix:
        node: [20.x]
    steps:
      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node_modules-${{ matrix.node }}-${{ hashFiles('package.json', 'yarn.lock') }}
          path: node_modules

      - name: Check if source or test files changed
        id: files_changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            src/**/*
            spec/**/*

      - name: Lint files
        if: ${{ steps.files_changed.outputs.any_modified == 'true' }}
        run: |
          yarn --ignore-engines --non-interactive
          yarn lint:ci

  build-and-test-pull-request:
    needs:
      - lint-pull-request
    name: Test
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        node: [16.x, 18.x, 20.x]
        module: [cjs, esm, umd]
        target: [es5, es2015, esnext]
        include:
          - {node: 16.x, target: ix}
          - {node: 18.x, target: ix}
          - {node: 20.x, target: ix}
          - {node: 20.x, target: src, args: --coverage}
    steps:
      - name: Setup node v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache targets
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-targets-${{ matrix.node }}-${{ matrix.target }}-${{ matrix.module }}-${{ hashFiles('package.json', 'yarn.lock', 'src/**/*') }}
          path: targets

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node_modules-${{ matrix.node }}-${{ hashFiles('package.json', 'yarn.lock') }}
          path: node_modules

      - name: Check if test files changed
        id: test_files_changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            spec/**/*

      - name: Check if source files changed
        id: source_files_changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .npmrc
            yarn.lock
            package.json
            src/**/*
            integration/**/*

      - name: Install dependencies
        if: ${{ steps.source_files_changed.outputs.any_modified	== 'true' || steps.test_files_changed.outputs.any_modified == 'true' }}
        run: |
          yarn --ignore-engines --non-interactive

      - name: Build package
        if: ${{ steps.source_files_changed.outputs.any_modified	== 'true' && matrix.target != 'src' }}
        env:
          t: "${{ matrix.target }}"
          m: "${{ matrix.module }}"
        run: |
          yarn build ${t:+-t ${t}} ${m:+-m ${m}}

      - name: Test package
        if: ${{ steps.source_files_changed.outputs.any_modified	== 'true' || steps.test_files_changed.outputs.any_modified == 'true' }}
        env:
          t: "${{ matrix.target }}"
          m: "${{ matrix.module }}"
        run: |
          yarn test ${t:+-t ${t}} ${m:+-m ${m}} ${{ matrix.args }}

  test-tree-shaking-pull-request:
    needs:
      - build-and-test-pull-request
    name: Integration
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        module: [cjs, esm, umd]
        target: [es5, es2015, esnext]
        bundler: [esbuild, rollup, webpack]
        include:
          - {target: ix, bundler: esbuild}
          - {target: ix, bundler: rollup}
          - {target: ix, bundler: webpack}
    steps:
      - name: Setup node v20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Cache targets
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-targets-20.x-ix--${{ hashFiles('package.json', 'yarn.lock', 'src/**/*') }}
          path: targets

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-node_modules-20.x-${{ hashFiles('package.json', 'yarn.lock') }}
          path: node_modules

      - name: Check if source files changed
        id: source_files_changed
        uses: tj-actions/changed-files@v44
        with:
          files: |
            .npmrc
            yarn.lock
            package.json
            src/**/*
            integration/**/*

      - name: Test ${{ matrix.bundler }} tree-shaking
        if: ${{ steps.source_files_changed.outputs.any_modified	== 'true' }}
        env:
          t: "${{ matrix.target }}"
          m: "${{ matrix.module }}"
        run: |
          integration/make-files-to-bundle.sh
          if test "${t}" != ix; then
            yarn build ${t:+-t ${t}} ${m:+-m ${m}}
          fi
          yarn gulp bundle${t:+:${t}}${m:+:${m}}:${{ matrix.bundler }}
