name: Build pull request

concurrency:
  group: pr-on-${{ github.event_name }}-from-${{ github.ref_name }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - "master"

jobs:
  lint-pull-request:
    name: Lint
    uses: ./.github/workflows/lint.yml

  build-and-test-pull-request:
    name: Test
    needs: lint-pull-request
    uses: ./.github/workflows/test.yml

  test-tree-shaking-pull-request:
    needs: build-and-test-pull-request
    name: Bundle
    uses: ./.github/workflows/bundle.yml
